[package]
name = "margaret_authorization_server_client_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
async-trait = { workspace = true }
http = { workspace = true }
margaret_authorization_server_client = { workspace = true }
margaret_http = { workspace = true }
margaret_http_tests = { path = "../margaret_http_tests" }
margaret_issuer_metadata = { workspace = true }
margaret_issuer_request = { workspace = true }
margaret_jwks_secret_store = { workspace = true }
margaret_jwt_verification_tests = { path = "../margaret_jwt_verification_tests" }
margaret_oauth_client = { workspace = true }
margaret_oauth_vocabulary = { workspace = true }
margaret_oidc_discovery = { workspace = true }
margaret_route_method = { workspace = true }
margaret_token_trust = { workspace = true }
margaret_trusted_issuer = { workspace = true }
oauth2 = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }

[dev-dependencies]
headers = { workspace = true }
margaret_jose_parameters = { workspace = true }
margaret_jwks_secret_store_tests = { path = "../margaret_jwks_secret_store_tests" }
margaret_jws_verification = { workspace = true }
margaret_token_signer_tests = { path = "../margaret_token_signer_tests" }
serde = { workspace = true, features = ["derive"] }
serde_path_to_error = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
