[package]
name = "margaret_container_tests"
version = "0.1.0"
edition = "2024"
autotests = false

[dependencies]
margaret_attribute_arguments = { path = "../margaret_attribute_arguments" }
margaret_attributes = { path = "../margaret_attributes" }
margaret_console_argument_codegen = { path = "../margaret_console_argument_codegen" }
margaret_container = { path = "../margaret_container" }
margaret_generated_module = { path = "../margaret_generated_module" }
syn = { workspace = true }

[dev-dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
