[package]
name = "margaret_container_tests"
version = "0.1.0"
edition = "2024"
autotests = false

[dependencies]
margaret_attributes = { path = "../margaret_attributes" }
margaret_container = { path = "../margaret_container" }
margaret_generated_module = { path = "../margaret_generated_module" }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
