[package]
name = "margaret_container_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
margaret_attribute_arguments = { workspace = true }
margaret_attributes = { workspace = true }
margaret_console_argument_codegen = { workspace = true }
margaret_container = { workspace = true }
margaret_generated_module = { workspace = true }
margaret_input_weaving = { workspace = true }
margaret_serve_input_codegen = { workspace = true }
margaret_token_issuance_codegen = { workspace = true }
syn = { workspace = true }

[dev-dependencies]
margaret_environment_variable_codegen = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
