[package]
name = "margaret_model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Model runtime types for the Margaret application framework."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[lints]
workspace = true
