[package]
name = "margaret_esbuild_metafile_codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
esbuild-metafile = { workspace = true }
margaret_attributes = { path = "../margaret_attributes" }
margaret_container = { path = "../margaret_container" }
proc-macro2 = { workspace = true }
quote = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
