[package]
name = "margaret_spiffe_svid_client_tests"
version = "0.1.0"
edition = "2024"
autotests = false

[dependencies]
margaret_spiffe_svid_client = { path = "../margaret_spiffe_svid_client" }
margaret_spiffe_svid_tests = { path = "../margaret_spiffe_svid_tests" }
rustls = { workspace = true }

[dev-dependencies]
margaret_spiffe_svid = { path = "../margaret_spiffe_svid" }
spiffe = { workspace = true, features = ["spiffe-types"] }
tokio = { workspace = true, features = ["macros", "rt"] }
tokio-util = { workspace = true }
trzcina = { workspace = true }

[lints]
workspace = true

[[test]]
name = "integration"
path = "tests/main.rs"
