[package]
name = "margaret_console"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Console command runtime support for the Margaret application framework."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }

[lints]
workspace = true
