[package]
name = "margaret_console"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
clap = { workspace = true }
margaret_http = { path = "../margaret_http" }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }

[lints]
workspace = true
