[package]
name = "margaret_jwks_keygen_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
margaret_jose_parameters = { workspace = true }
margaret_jwks_keygen = { workspace = true }
margaret_jws_verification = { workspace = true }
margaret_jwt_verification = { workspace = true }
margaret_jwt_verification_tests = { path = "../margaret_jwt_verification_tests" }
margaret_registered_claims = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
base64ct = { workspace = true }
jsonwebtoken = { workspace = true }
p256 = { workspace = true }
zeroize = { workspace = true }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
