[package]
name = "margaret_jwks_keygen_tests"
version = "0.1.0"
edition = "2024"
autotests = false

[dependencies]
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
anyhow = { workspace = true }
base64ct = { workspace = true }
jsonwebtoken = { workspace = true }
margaret_jwks_keygen = { path = "../margaret_jwks_keygen" }
p256 = { workspace = true }
p384 = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
zeroize = { workspace = true }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
