[package]
name = "margaret_container"
version = "0.1.0"
edition = "2024"
autotests = false

[dependencies]
margaret_attributes = { path = "../margaret_attributes" }
margaret_generated_module = { path = "../margaret_generated_module" }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
