[package]
name = "margaret_identity"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true, features = ["clock"] }
clap = { workspace = true }
margaret_console = { path = "../margaret_console" }
margaret_http = { path = "../margaret_http" }
margaret_http_validation = { path = "../margaret_http_validation" }
margaret_identity_session = { path = "../margaret_identity_session" }
margaret_jwks_key_gen = { path = "../margaret_jwks_key_gen" }
margaret_jwks_roller = { path = "../margaret_jwks_roller" }
margaret_macros = { path = "../margaret_macros" }
margaret_service = { path = "../margaret_service" }
margaret_spiffe_svid_manager = { path = "../margaret_spiffe_svid_manager" }
margaret_token_signer = { path = "../margaret_token_signer" }
margaret_validation = { path = "../margaret_validation" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
spiffe = { workspace = true, features = ["spiffe-types"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-util = { workspace = true }
trzcina = { workspace = true }
validator = { workspace = true, features = ["derive"] }

[build-dependencies]
margaret_codegen = { path = "../margaret_codegen" }

[lints]
workspace = true
