[package]
name = "margaret_jwks_roller_server"
version = "0.1.0"
edition = "2024"
autotests = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
margaret_http = { path = "../margaret_http" }
margaret_jwks_keygen = { path = "../margaret_jwks_keygen" }
margaret_jwks_roller = { path = "../margaret_jwks_roller" }
margaret_sync_holder = { path = "../margaret_sync_holder" }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio-util = { workspace = true }
trzcina = { workspace = true }

[dev-dependencies]
http = { workspace = true }
margaret_identity_session = { path = "../margaret_identity_session" }
margaret_jwks_roller_tests = { path = "../margaret_jwks_roller_tests" }
tokio = { workspace = true, features = ["macros", "rt", "test-util"] }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
