[package]
name = "margaret_spiffe_svid_bundle"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Bundled SPIFFE SVID client and server support for the Margaret application framework."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
margaret_spiffe_svid = { workspace = true }
margaret_spiffe_svid_client = { workspace = true }
margaret_spiffe_svid_server = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
thiserror = { workspace = true }
trzcina = { workspace = true }

[lints]
workspace = true
