[package]
name = "margaret_codegen_linear_construction_future_fixture"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = { workspace = true }
margaret = { path = "../../../../margaret" }

[build-dependencies]
margaret = { path = "../../../../margaret", default-features = false, features = ["codegen"] }

[lints]
workspace = true
