[package]
name = "margaret_schema_codegen"
version = "0.3.0"
edition.workspace = true
rust-version.workspace = true
description = "Database schema code generation for the Margaret application framework."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
margaret_codegen_tokens = { workspace = true }
margaret_generated_module = { workspace = true }
margaret_model = { workspace = true }
margaret_model_codegen = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }

[dev-dependencies]
margaret_attributes = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
