[package]
name = "margaret_codegen_tests"
version = "0.1.0"
edition = "2024"
autotests = false

[lib]
doctest = false
test = false

[dependencies]
margaret_attributes = { path = "../margaret_attributes" }
margaret_codegen = { path = "../margaret_codegen" }

[dev-dependencies]
margaret_console_argument_codegen = { path = "../margaret_console_argument_codegen" }
margaret_codegen_fallible_roles_fixture = { path = "tests/fixtures/fallible_roles" }
margaret_codegen_linear_construction_future_fixture = { path = "tests/fixtures/linear_construction_future" }
tokio = { workspace = true, features = ["macros", "rt"] }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
