[package]
name = "margaret_asset_bag"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Runtime asset collection support for the Margaret application framework."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
dashmap = { workspace = true }
maud = { workspace = true }

[lints]
workspace = true
