[package]
name = "margaret_store_contract_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
chrono = { workspace = true, features = ["clock"] }
futures-util = { workspace = true }
margaret_accepted_clients = { workspace = true }
margaret_authorization_grants = { workspace = true }
margaret_jwks_keygen = { workspace = true }
margaret_jwks_keygen_tests = { path = "../margaret_jwks_keygen_tests" }
margaret_jwks_roller = { workspace = true }
margaret_oauth_vocabulary = { workspace = true }
margaret_registered_claims = { workspace = true }
margaret_token_digest = { workspace = true }
url = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
margaret_accepted_clients_tests = { path = "../margaret_accepted_clients_tests" }
margaret_jwks_roller_tests = { path = "../margaret_jwks_roller_tests" }
margaret_oidc_provider_tests = { path = "../margaret_oidc_provider_tests" }
tokio = { workspace = true, features = ["macros", "rt"] }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
