[package]
name = "margaret_spiffe_svid"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true }
margaret_peer_identity = { path = "../margaret_peer_identity" }
margaret_sync_holder = { path = "../margaret_sync_holder" }
rustls = { workspace = true }
spiffe = { workspace = true, features = ["spiffe-types", "workload-api"] }
tokio = { workspace = true, features = ["macros", "rt", "sync"] }
tokio-util = { workspace = true }
trzcina = { workspace = true }
url = { workspace = true }
x509-parser = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "time"] }

[lints]
workspace = true
