[package]
name = "margaret_client_assertions_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
margaret_accepted_clients = { workspace = true }
margaret_client_assertions = { workspace = true }
margaret_database_tests = { path = "../margaret_database_tests" }
margaret_model = { workspace = true }
margaret_registered_claims = { workspace = true }

[dev-dependencies]
futures-util = { workspace = true }
margaret = { workspace = true, features = ["runtime"] }
tokio = { workspace = true, features = ["macros", "rt"] }

[features]
tests_that_use_postgres = []

[[test]]
name = "postgres"
path = "tests/main.rs"

[lints]
workspace = true
