[package]
name = "margaret_provider_state_postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Keeps the state of an OpenID Connect provider in Postgres for the Margaret application framework."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
async-trait = { workspace = true }
margaret_model = { workspace = true }
margaret_oauth_vocabulary = { workspace = true }
margaret_provider_state_storage = { workspace = true }
margaret_registered_claims = { workspace = true }
margaret_token_digest = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[lints]
workspace = true
