[package]
name = "margaret_spiffe_svid_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true }
margaret_sync_holder = { path = "../margaret_sync_holder" }
reqwest = { workspace = true }
rustls = { workspace = true }
rustls-webpki = { workspace = true }
spiffe = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
tokio-util = { workspace = true }
trzcina = { workspace = true }
url = { workspace = true }
x509-parser = { workspace = true }

[lints]
workspace = true
