[package]
name = "margaret_access_token_minter"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
margaret_http = { path = "../margaret_http" }
margaret_jwks_secret_store = { path = "../margaret_jwks_secret_store" }
margaret_token_signer = { path = "../margaret_token_signer" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
http = { workspace = true }
margaret_jwks_keygen = { path = "../margaret_jwks_keygen" }
margaret_token_signer_tests = { path = "../margaret_token_signer_tests" }
tokio = { workspace = true, features = ["macros", "rt"] }
tokio-util = { workspace = true }

[lints]
workspace = true
