[package]
name = "margaret_websocket_codegen"
version = "0.3.1"
edition.workspace = true
rust-version.workspace = true
description = "WebSocket code generation for the Margaret application framework."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
margaret_attribute_arguments = { workspace = true }
margaret_attributes = { workspace = true }
margaret_codegen_tokens = { workspace = true }
margaret_console_argument_codegen = { workspace = true }
margaret_container = { workspace = true }
margaret_generated_module = { workspace = true }
margaret_injection_codegen = { workspace = true }
margaret_middleware_codegen = { workspace = true }
margaret_request_binding_codegen = { workspace = true }
margaret_route_parameter_codegen = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
