[package]
name = "margaret_item_naming_argument"
version = "0.4.0"
edition.workspace = true
rust-version.workspace = true
description = "Attribute arguments that name Rust items in the Margaret application framework."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
margaret_attribute_arguments = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }

[dev-dependencies]
syn = { workspace = true }

[lints]
workspace = true
