[package]
name = "margaret_jwks_client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "JWKS client support for the Margaret application framework."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
margaret_issuer_document_fetch = { workspace = true }
margaret_jwks_endpoint = { workspace = true }
margaret_jws_verification = { workspace = true }
margaret_jwt_verification = { workspace = true }
margaret_registered_claims = { workspace = true }
margaret_sync_holder = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "time"] }
tokio-util = { workspace = true }
trzcina = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "test-util"] }
url = { workspace = true }

[lints]
workspace = true
