[package]
name = "margaret_http_validation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "HTTP request validation for the Margaret application framework."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
margaret_http = { workspace = true }
margaret_validation = { workspace = true }
serde = { workspace = true }
validator = { workspace = true }

[dev-dependencies]
http = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
validator = { workspace = true, features = ["derive"] }

[lints]
workspace = true
