[package]
name = "margaret_http_validation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "HTTP request validation for the Margaret application framework."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
anyhow = { workspace = true }
margaret_handler_error = { workspace = true }
margaret_http = { workspace = true }
margaret_validation = { workspace = true }
serde = { workspace = true }
validator = { workspace = true }

[dev-dependencies]
http = { workspace = true }
margaret_http_tests = { path = "../margaret_http_tests" }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "rt"] }
validator = { workspace = true, features = ["derive"] }

[lints]
workspace = true
