pub mod client_sign_in;
pub mod client_sign_ins;
mod marked_callback;
mod marked_endpoint;
mod marked_sign_in_endpoints;
mod marked_start;
pub mod served_sign_in;
mod sign_in_admission_declaration;
mod sign_in_admissions;
pub mod sign_in_callback;
mod sign_in_client;
mod sign_in_endpoint_variant;
pub mod sign_in_endpoints_codegen_error;
mod sign_in_endpoints_vocabulary;
pub mod sign_in_service;
