[package]
name = "margaret_codegen_websocket_fixture"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
margaret = { workspace = true, features = ["runtime"] }
maud = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
tokio-util = { workspace = true }
trzcina = { workspace = true }
validator = { workspace = true, features = ["derive"] }

[build-dependencies]
margaret = { workspace = true, default-features = false, features = ["codegen"] }

[lints]
workspace = true
