[package]
name = "margaret_syn_type_peeling"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Rust syntax type analysis for the Margaret application framework."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
syn = { workspace = true }

[dev-dependencies]
quote = { workspace = true }

[lints]
workspace = true
