[package]
name = "margaret_jwks_client_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
margaret_bearer_token_verification = { workspace = true }
margaret_http = { workspace = true }
margaret_http_tests = { path = "../margaret_http_tests" }
margaret_jwks_client = { workspace = true }
margaret_jwks_endpoint = { workspace = true }
margaret_jwks_keygen = { workspace = true }
margaret_jwks_roller = { workspace = true }
margaret_jwks_roller_server = { workspace = true }
margaret_jwt_verification_tests = { path = "../margaret_jwt_verification_tests" }
margaret_sync_holder = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
tokio-util = { workspace = true }
trzcina = { workspace = true }
url = { workspace = true }

[dev-dependencies]
margaret_jwks_keygen_tests = { path = "../margaret_jwks_keygen_tests" }
margaret_key_set_poll = { workspace = true }
margaret_key_set_poll_tests = { path = "../margaret_key_set_poll_tests" }
margaret_registered_claims = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "test-util", "time"] }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
