[package]
name = "margaret_jwks_client_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
margaret_jwks_endpoint = { workspace = true }
margaret_http = { workspace = true }
margaret_http_uploaded_file = { workspace = true }
margaret_identity_session = { workspace = true }
margaret_jwks_roller = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "test-util", "time"] }
tokio-util = { workspace = true }
trzcina = { workspace = true }
url = { workspace = true }

[dev-dependencies]
margaret_http_tests = { path = "../margaret_http_tests" }
margaret_jwks_client = { workspace = true }
margaret_jwks_keygen = { workspace = true }
margaret_jwks_roller_server = { workspace = true }
margaret_sync_holder = { workspace = true }
reqwest = { workspace = true }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
