[package]
name = "margaret_codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
margaret_asset_codegen = { path = "../margaret_asset_codegen" }
margaret_attributes = { path = "../margaret_attributes" }
margaret_console_argument_codegen = { path = "../margaret_console_argument_codegen" }
margaret_console_codegen = { path = "../margaret_console_codegen" }
margaret_container = { path = "../margaret_container" }
margaret_generated_module = { path = "../margaret_generated_module" }
margaret_http_codegen = { path = "../margaret_http_codegen" }
margaret_service_codegen = { path = "../margaret_service_codegen" }
margaret_views_codegen = { path = "../margaret_views_codegen" }
thiserror = { workspace = true }

[dev-dependencies]
quote = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
