[package]
name = "margaret_codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
margaret_attributes = { path = "../margaret_attributes" }
margaret_console_codegen = { path = "../margaret_console_codegen" }
margaret_container = { path = "../margaret_container" }
margaret_http_codegen = { path = "../margaret_http_codegen" }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
