[package]
name = "margaret_authorization_grants_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
margaret = { workspace = true, features = ["runtime"] }
margaret_authorization_grants = { workspace = true }
margaret_database_tests = { path = "../margaret_database_tests" }
margaret_model = { workspace = true }
margaret_oauth_vocabulary = { workspace = true }
margaret_registered_claims = { workspace = true }
margaret_token_digest = { workspace = true }
url = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
futures-util = { workspace = true }
margaret_sql_identifier = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }

[features]
tests_that_use_postgres = []

[[test]]
name = "postgres"
path = "tests/main.rs"

[lints]
workspace = true
