[package]
name = "margaret_console_codegen"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
description = "Console command code generation for the Margaret application framework."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
margaret_attribute_arguments = { workspace = true }
margaret_attributes = { workspace = true }
margaret_codegen_tokens = { workspace = true }
margaret_container = { workspace = true }
margaret_console_argument_codegen = { workspace = true }
margaret_generated_module = { workspace = true }
margaret_http_codegen = { workspace = true }
margaret_injection_codegen = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
