[package]
name = "margaret_jwks_secret_store_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
margaret_jwks_keygen = { workspace = true }
margaret_jwks_keygen_tests = { path = "../margaret_jwks_keygen_tests" }
margaret_jwks_roller = { workspace = true }
margaret_jwks_roller_server = { workspace = true }
margaret_jwks_roller_tests = { path = "../margaret_jwks_roller_tests" }
margaret_jwks_secret_store = { workspace = true }
margaret_token_signer_tests = { path = "../margaret_token_signer_tests" }

[dev-dependencies]
aws-lc-rs = { workspace = true }
margaret_identity_session = { workspace = true }
margaret_jose_parameters = { workspace = true }
margaret_jws_verification = { workspace = true }
margaret_jwt_verification = { workspace = true }
margaret_registered_claims = { workspace = true }
margaret_token_signer = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
uuid = { workspace = true }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
