[package]
name = "margaret_environment_variable"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Environment variable input reading for the Margaret application framework."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
thiserror = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
margaret_process_tests = { path = "../margaret_process_tests" }

[lints]
workspace = true
