mod peer_identity_is_anonymous_without_a_certificate;
mod peer_identity_is_unidentified_for_a_non_spiffe_certificate;
mod peer_identity_is_verified_for_a_spiffe_certificate;
mod spiffe_id_from_cert_extracts_a_spiffe_id;
mod spiffe_id_from_cert_rejects_malformed_der;
mod spiffe_id_from_cert_rejects_multiple_uris;
mod spiffe_id_from_cert_rejects_a_non_spiffe_uri;
mod spiffe_id_from_cert_reports_a_missing_uri;
