[package]
name = "margaret_example"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true, features = ["clock"] }
clap = { workspace = true }
dashmap = { workspace = true }
margaret_asset_bag = { path = "../margaret_asset_bag" }
margaret_console = { path = "../margaret_console" }
margaret_http = { path = "../margaret_http" }
margaret_http_validation = { path = "../margaret_http_validation" }
margaret_jwks_roller = { path = "../margaret_jwks_roller" }
margaret_jwks_roller_server = { path = "../margaret_jwks_roller_server" }
margaret_macros = { path = "../margaret_macros" }
margaret_model = { path = "../margaret_model" }
margaret_service = { path = "../margaret_service" }
margaret_spiffe_svid = { path = "../margaret_spiffe_svid" }
margaret_spiffe_svid_server = { path = "../margaret_spiffe_svid_server" }
margaret_validation = { path = "../margaret_validation" }
margaret_views = { path = "../margaret_views" }
margaret_websocket = { path = "../margaret_websocket" }
maud = { workspace = true }
rust-embed = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
spiffe = { workspace = true, features = ["spiffe-types"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-util = { workspace = true }
trzcina = { workspace = true }
uuid = { workspace = true, features = ["serde"] }
validator = { workspace = true, features = ["derive"] }

[build-dependencies]
margaret_codegen = { path = "../margaret_codegen" }

[lints]
workspace = true
