[package]
name = "margaret_example"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true, features = ["clock"] }
clap = { workspace = true }
cookie = { workspace = true }
margaret = { workspace = true, features = ["runtime"] }
maud = { workspace = true }
rust_decimal = { workspace = true, features = ["db-tokio-postgres"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
spiffe = { workspace = true, features = ["spiffe-types"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-util = { workspace = true }
trzcina = { workspace = true }
url = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }
validator = { workspace = true, features = ["derive"] }

[build-dependencies]
margaret = { workspace = true, default-features = false, features = ["codegen"] }

[lints]
workspace = true
