[package]
name = "margaret_example"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true, features = ["clock"] }
clap = { workspace = true }
dashmap = { workspace = true }
margaret = { path = "../margaret" }
maud = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
spiffe = { workspace = true, features = ["spiffe-types"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-util = { workspace = true }
trzcina = { workspace = true }
url = { workspace = true }
uuid = { workspace = true, features = ["serde"] }
validator = { workspace = true, features = ["derive"] }

[build-dependencies]
margaret = { path = "../margaret", default-features = false, features = ["codegen"] }

[lints]
workspace = true
