[package]
name = "margaret_validation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Validation error types for the Margaret application framework."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
validator = { workspace = true }

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
validator = { workspace = true, features = ["derive"] }

[lints]
workspace = true
