[package]
name = "margaret_codegen_collisions_and_diamonds_fixture"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
margaret = { path = "../../../../margaret" }
tokio = { workspace = true, features = ["macros", "rt"] }
tokio-util = { workspace = true }
trzcina = { workspace = true }

[build-dependencies]
margaret = { path = "../../../../margaret", default-features = false, features = ["codegen"] }

[lints]
workspace = true
