[package]
name = "margaret_spiffe_svid_integration_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dev-dependencies]
margaret_spiffe_svid = { workspace = true }
margaret_spiffe_svid_bundle = { workspace = true }
margaret_spiffe_svid_tests = { path = "../margaret_spiffe_svid_tests" }
margaret_sync_holder = { workspace = true }
rustls = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "net", "process", "rt-multi-thread", "sync", "time"] }
tokio-util = { workspace = true }
trzcina = { workspace = true }

[features]
tests_that_use_spire = []

[lints]
workspace = true

[[test]]
name = "integration"
path = "tests/main.rs"
