[package]
name = "margaret_signing_keys_schema"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "The table in which a Margaret application keeps its signing keys."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
margaret_macros = { workspace = true }

[lints]
workspace = true
