[package]
name = "margaret_oidc_provider_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true, features = ["clock"] }
form_urlencoded = { workspace = true }
headers = { workspace = true }
http = { workspace = true }
margaret_accepted_clients = { workspace = true }
margaret_accepted_clients_tests = { path = "../margaret_accepted_clients_tests" }
margaret_authorization_grants = { workspace = true }
margaret_authorization_server_client = { workspace = true }
margaret_authorization_server_client_tests = { path = "../margaret_authorization_server_client_tests" }
margaret_http = { workspace = true }
margaret_http_tests = { path = "../margaret_http_tests" }
margaret_issuer_directory = { workspace = true }
margaret_issuer_directory_tests = { path = "../margaret_issuer_directory_tests" }
margaret_issuer_key_set = { workspace = true }
margaret_issuer_metadata = { workspace = true }
margaret_issuer_request = { workspace = true }
margaret_jose_parameters = { workspace = true }
margaret_jwks_keygen = { workspace = true }
margaret_jwks_roller_server = { workspace = true }
margaret_jwks_secret_store = { workspace = true }
margaret_jwks_secret_store_tests = { path = "../margaret_jwks_secret_store_tests" }
margaret_jws_verification = { workspace = true }
margaret_jwt_verification = { workspace = true }
margaret_jwt_verification_tests = { path = "../margaret_jwt_verification_tests" }
margaret_oauth_vocabulary = { workspace = true }
margaret_oidc_discovery = { workspace = true }
margaret_oidc_provider = { workspace = true }
margaret_oidc_sign_in = { workspace = true }
margaret_oidc_sign_in_tests = { path = "../margaret_oidc_sign_in_tests" }
margaret_registered_claims = { workspace = true }
margaret_route_method = { workspace = true }
margaret_subject_token_exchange = { workspace = true }
margaret_token_digest = { workspace = true }
margaret_token_issuance = { workspace = true }
margaret_token_signer_tests = { path = "../margaret_token_signer_tests" }
margaret_token_trust = { workspace = true }
margaret_trusted_issuer = { workspace = true }
margaret_validation = { workspace = true }
oauth2 = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }
url = { workspace = true }
uuid = { workspace = true }
validator = { workspace = true }

[dev-dependencies]
margaret_bearer_token_verification = { workspace = true }
margaret_client_credentials = { workspace = true }
margaret_identity_session = { workspace = true }
margaret_token_exchange_client = { workspace = true }
margaret_token_introspection = { workspace = true }
zeroize = { workspace = true }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
