mod key_set_poll_interval_before_ready_is_shorter_than_after_ready;
mod key_set_poll_service_does_not_wait_before_the_first_key_is_fetched;
mod key_set_poll_service_reports_a_document_that_is_not_a_key_set;
mod key_set_poll_service_reports_an_error_status_of_the_issuer;
mod key_set_poll_service_retains_the_last_set_when_the_issuer_is_unreachable;
mod key_set_poll_service_retains_the_last_set_when_the_key_set_cannot_be_located;
mod key_set_poll_service_returns_promptly_when_cancelled_during_the_wait;
mod key_set_poll_service_waits_the_steady_interval_after_a_key_is_held;
