[package]
name = "margaret_subject_token_exchange_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
chrono = { workspace = true, features = ["clock"] }
margaret_issuer_metadata = { workspace = true }
margaret_jose_parameters = { workspace = true }
margaret_jwks_keygen = { workspace = true }
margaret_jwt_verification = { workspace = true }
margaret_subject_token_exchange = { workspace = true }
margaret_token_signer_tests = { path = "../margaret_token_signer_tests" }
margaret_token_trust = { workspace = true }
margaret_trusted_issuer = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
margaret_jws_verification = { workspace = true }
margaret_oauth_vocabulary = { workspace = true }
margaret_token_exchange_client = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
