[package]
name = "margaret_jwks_roller_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
anyhow = { workspace = true }
margaret_jwks_keygen = { path = "../margaret_jwks_keygen" }
margaret_jwks_roller = { path = "../margaret_jwks_roller" }
thiserror = { workspace = true }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
