[package]
name = "margaret_jwks_roller_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
margaret_jwks_keygen = { workspace = true }
margaret_jwks_keygen_tests = { path = "../margaret_jwks_keygen_tests" }
margaret_jwks_roller = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
futures-util = { workspace = true }
margaret_identity_session = { workspace = true }
margaret_issuer_request = { workspace = true }
margaret_registered_claims = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync"] }
zeroize = { workspace = true }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
