[package]
name = "margaret_jwks_secret_storage_selection_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dev-dependencies]
anyhow = { workspace = true }
margaret_jose_parameters = { workspace = true }
margaret_jwks_keygen = { workspace = true }
margaret_jwks_keygen_tests = { path = "../margaret_jwks_keygen_tests" }
margaret_jwks_roller = { workspace = true }
margaret_jwks_secret_storage_selection = { workspace = true }
margaret_storage_uri = { workspace = true }
tempfile = { workspace = true }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
