[package]
name = "margaret_key_set_poll_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
async-trait = { workspace = true }
margaret_issuer_document_fetch = { workspace = true }
margaret_key_set_poll = { workspace = true }
reqwest = { workspace = true }
trzcina = { workspace = true }
url = { workspace = true }

[dev-dependencies]
margaret_http = { workspace = true }
margaret_http_tests = { path = "../margaret_http_tests" }
margaret_jose_parameters = { workspace = true }
margaret_jws_verification = { workspace = true }
margaret_jws_verification_tests = { path = "../margaret_jws_verification_tests" }
margaret_sync_holder = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "test-util", "time"] }
tokio-util = { workspace = true }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
