[package]
name = "margaret_codegen_jwks_token_trust_fixture"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
margaret = { workspace = true, features = ["runtime"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
tokio-util = { workspace = true }
trzcina = { workspace = true }
url = { workspace = true }

[build-dependencies]
margaret = { workspace = true, default-features = false, features = ["codegen"] }

[lints]
workspace = true
