mod memory_state_approves_a_pending_authorization_into_a_code;
mod memory_state_denies_a_pending_authorization;
mod memory_state_forgets_a_pending_authorization_decided_by_another_subject;
mod memory_state_opens_a_refresh_family_when_spending_a_code;
mod memory_state_refuses_to_revoke_a_refresh_token_of_another_client;
mod memory_state_reports_an_expired_client_assertion;
mod memory_state_reports_an_unknown_authorization_code;
mod memory_state_reports_an_unknown_refresh_token;
mod memory_state_reports_the_revocation_of_an_unknown_refresh_token;
mod memory_state_reports_the_rotation_of_an_unknown_refresh_token;
mod memory_state_reports_the_spending_of_an_unknown_code;
mod memory_state_revokes_the_family_of_a_code_spent_concurrently;
mod memory_state_revokes_the_family_of_a_refresh_token;
mod memory_state_revokes_the_family_of_a_refresh_token_rotated_concurrently;
mod memory_state_revokes_the_family_of_a_replayed_refresh_token;
mod memory_state_revokes_the_refresh_family_of_a_replayed_code;
mod memory_state_rotates_a_current_refresh_token;
mod memory_state_spends_a_client_assertion_once;
mod memory_state_spends_a_client_assertion_presented_concurrently_once;
mod memory_state_spends_an_assertion_again_once_its_record_expired;
mod memory_state_spends_an_authorization_code_once;
mod memory_state_spends_the_assertions_of_distinct_clients_independently;
#[cfg(feature = "tests_that_use_postgres")]
mod postgres_state_honours_the_storage_contract;
#[cfg(feature = "tests_that_use_postgres")]
mod postgres_state_purges_expired_client_assertions;
#[cfg(feature = "tests_that_use_postgres")]
mod postgres_state_reports_every_operation_without_its_tables;
#[cfg(feature = "tests_that_use_postgres")]
mod postgres_state_reports_unreadable_documents;
#[cfg(feature = "tests_that_use_postgres")]
mod postgres_state_revokes_the_family_of_a_code_spent_behind_a_held_lock;
#[cfg(feature = "tests_that_use_postgres")]
mod postgres_state_spends_a_client_assertion_behind_a_held_lock_once;
