mod digests_a_token_with_sha256;
mod memory_state_approves_a_pending_authorization_into_a_code;
mod memory_state_burns_a_code_presented_by_another_client;
mod memory_state_burns_a_code_presented_with_another_callback;
mod memory_state_burns_a_code_presented_with_another_challenge;
mod memory_state_denies_a_pending_authorization;
mod memory_state_forgets_a_pending_authorization_decided_by_another_subject;
mod memory_state_opens_a_refresh_family_when_redeeming_a_code;
mod memory_state_redeems_an_authorization_code_once;
mod memory_state_refuses_to_revoke_a_refresh_token_of_another_client;
mod memory_state_refuses_to_rotate_a_token_beyond_its_granted_scope;
mod memory_state_refuses_to_rotate_a_token_for_another_client;
mod memory_state_reports_an_unknown_authorization_code;
mod memory_state_reports_an_unknown_refresh_token;
mod memory_state_reports_the_revocation_of_an_unknown_refresh_token;
mod memory_state_revokes_the_family_of_a_refresh_token;
mod memory_state_revokes_the_family_of_a_replayed_refresh_token;
mod memory_state_revokes_the_refresh_family_of_a_replayed_code;
mod memory_state_rotates_a_current_refresh_token;
mod memory_state_rotates_a_token_narrowed_within_its_granted_scope;
#[cfg(feature = "tests_that_use_postgres")]
mod postgres_state_honours_the_storage_contract;
#[cfg(feature = "tests_that_use_postgres")]
mod postgres_state_reports_every_operation_without_its_tables;
#[cfg(feature = "tests_that_use_postgres")]
mod postgres_state_reports_unreadable_documents;
