[package]
name = "margaret_service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Application service runtime support for the Margaret application framework."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
margaret_console = { workspace = true }
margaret_http = { workspace = true }
margaret_http_uploaded_file = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "signal"] }
tokio-util = { workspace = true }
trzcina = { workspace = true }

[dev-dependencies]
libc = { workspace = true }

[lints]
workspace = true
