[package]
name = "margaret_service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
margaret_console = { path = "../margaret_console" }
margaret_http = { path = "../margaret_http" }
tokio = { workspace = true, features = ["macros", "rt", "signal"] }
tokio-util = { workspace = true }
trzcina = { workspace = true }

[dev-dependencies]
libc = { workspace = true }

[lints]
workspace = true
