[package]
name = "margaret_schema_postgres_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
ephemeral-postgres = { workspace = true }
margaret_model = { path = "../margaret_model" }
sqlx = { workspace = true }

[dev-dependencies]
chrono = { workspace = true, features = ["clock"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
uuid = { workspace = true, features = ["v4"] }

[features]
tests_that_use_postgres = []

[lints]
workspace = true

[[test]]
name = "integration"
path = "tests/main.rs"
