[package]
name = "margaret_schema_postgres_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
ephemeral-postgres = { workspace = true }
margaret_database = { workspace = true }
margaret_model = { workspace = true }

[dev-dependencies]
chrono = { workspace = true, features = ["clock"] }
margaret_schema_postgres_fixture = { path = "fixture" }
rust_decimal = { workspace = true, features = ["db-tokio-postgres"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-postgres = { workspace = true, features = ["with-chrono-0_4", "with-uuid-1"] }
uuid = { workspace = true, features = ["v4"] }

[features]
tests_that_use_postgres = []

[lints]
workspace = true

[[test]]
name = "integration"
path = "tests/main.rs"
