[package]
name = "margaret_peer_identity"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Peer identity extraction for the Margaret application framework."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
log = { workspace = true }
spiffe = { workspace = true, features = ["spiffe-types"] }
thiserror = { workspace = true }
x509-parser = { workspace = true }

[lints]
workspace = true
