[package]
name = "margaret_service_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]

[dev-dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
margaret_console = { workspace = true }
margaret_handler_error = { workspace = true }
margaret_http = { workspace = true }
margaret_http_uploaded_file = { workspace = true }
margaret_process_tests = { path = "../margaret_process_tests" }
margaret_route_method = { workspace = true }
margaret_service = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt-multi-thread", "test-util", "time"] }
tokio-util = { workspace = true }
trzcina = { workspace = true }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
