use thiserror::Error;

use margaret_attribute_arguments::attribute_arguments_error::AttributeArgumentsError;
use margaret_attributes::attribute_error::AttributeError;
use margaret_schema_identifier_naming::schema_identifier_naming_error::SchemaIdentifierNamingError;

#[derive(Debug, Error)]
pub enum ModelCodegenError {
    #[error(
        "relation '{relation}' of model '{model}' is covered by several indexes of its related model that lead with '{key}'; keep exactly one index that orders the related rows"
    )]
    AmbiguousHasManyIndex {
        key: String,
        model: String,
        relation: String,
    },

    #[error("failed to read the attribute arguments: {source}")]
    AttributeArguments {
        #[from]
        source: AttributeArgumentsError,
    },

    #[error("model '{model}' derives a byte length constraint name that is too long: {source}")]
    ByteLengthConstraintNameTooLong {
        model: String,
        #[source]
        source: SchemaIdentifierNamingError,
    },

    #[error("field '{field}' of model '{model}' declares a byte_length of zero")]
    ByteLengthMustBePositive { field: String, model: String },

    #[error(
        "column '{column}' of model '{model}' declares a byte_length, which only applies to Vec<u8> columns"
    )]
    ByteLengthOnNonByteaColumn { column: String, model: String },

    #[error(
        "field '{field}' of model '{model}' declares a column default outside its primary key; only primary key columns are generated by the database"
    )]
    ColumnDefaultOutsidePrimaryKey { field: String, model: String },

    #[error(
        "field '{field}' of model '{model}' declares the uuidv7 column default on a column that is not a Uuid"
    )]
    ColumnDefaultRequiresUuidColumn { field: String, model: String },

    #[error("model '{model}' derives a column name that is too long: {source}")]
    ColumnNameTooLong {
        model: String,
        #[source]
        source: SchemaIdentifierNamingError,
    },

    #[error(
        "model '{model}' flags several fields with #[column(primary_key)]; declare a composite primary key with #[primary_key(fields = [...])]"
    )]
    CompositePrimaryKeyRequiresModelDeclaration { model: String },

    #[error("field '{field}' of model '{model}' declares both byte_length and minimum")]
    ConflictingColumnChecks { field: String, model: String },

    #[error(
        "model '{model}' declares its primary key with both #[primary_key] and #[column(primary_key)]"
    )]
    ConflictingPrimaryKeyDeclarations { model: String },

    #[error(
        "the constraint index '{name}' of table '{constraint_table}' collides with the table of model '{table_model}'"
    )]
    ConstraintIndexCollidesWithTableName {
        constraint_table: String,
        name: String,
        table_model: String,
    },

    #[error("model '{model}' has a duplicate column name '{column}'")]
    DuplicateColumnName { column: String, model: String },

    #[error(
        "the constraint index '{name}' is derived by both table '{first_table}' and table '{second_table}'"
    )]
    DuplicateConstraintIndexName {
        first_table: String,
        name: String,
        second_table: String,
    },

    #[error("model '{model}' declares more than one index named '{index}'")]
    DuplicateIndexDeclaration { index: String, model: String },

    #[error("the index '{name}' is declared by both table '{first}' and table '{second}'")]
    DuplicateIndexName {
        first: String,
        name: String,
        second: String,
    },

    #[error(
        "model '{model}' declares more than one relation through the key '{key}' of model '{related}'"
    )]
    DuplicateInverseRelation {
        key: String,
        model: String,
        related: String,
    },

    #[error("model '{model}' declares more than one unique constraint on the fields '{fields}'")]
    DuplicateModelUniqueConstraint { fields: String, model: String },

    #[error(
        "model '{model}' declares the relation '{relation}' more than once, or names it after one of its own key fields"
    )]
    DuplicateRelationName { model: String, relation: String },

    #[error("duplicate table name '{table}' declared by both '{first}' and '{second}'")]
    DuplicateTableName {
        first: String,
        second: String,
        table: String,
    },

    #[error(
        "field '{field}' of model '{model}' has the type '{enum_type}', an enum without variants"
    )]
    EmptyEnumColumn {
        enum_type: String,
        field: String,
        model: String,
    },

    #[error(
        "field '{field}' of model '{model}' has the type '{enum_type}', whose variant '{variant}' carries data; an enum column only stores unit variants"
    )]
    EnumColumnVariantNotUnit {
        enum_type: String,
        field: String,
        model: String,
        variant: String,
    },

    #[error("model '{model}' declares the index name '{index}', which is too long: {source}")]
    ExplicitIndexNameTooLong {
        index: String,
        model: String,
        #[source]
        source: SchemaIdentifierNamingError,
    },

    #[error(
        "field '{field}' of model '{model}' declares the fields of its #[index]; a field index covers the field itself"
    )]
    FieldIndexCannotDeclareFields { field: String, model: String },

    #[error("field '{field}' of model '{model}' must be a snake_case identifier")]
    FieldNameNotSnakeCase { field: String, model: String },

    #[error(
        "key field '{field}' of model '{model}' declares a check constraint; its columns mirror the referenced primary key"
    )]
    ForeignKeyCannotDeclareCheckConstraint { field: String, model: String },

    #[error(
        "key field '{field}' of model '{model}' declares a column default; its columns mirror the referenced primary key"
    )]
    ForeignKeyCannotDeclareDefault { field: String, model: String },

    #[error(
        "key field '{field}' of model '{model}' declares a column name; its column names are derived from the referenced primary key"
    )]
    ForeignKeyColumnNameIsDerived { field: String, model: String },

    #[error(
        "key field '{field}' of model '{model}' derives a column name that is too long: {source}"
    )]
    ForeignKeyColumnNameTooLong {
        field: String,
        model: String,
        #[source]
        source: SchemaIdentifierNamingError,
    },

    #[error("the foreign keys of the models form a cycle: {path}")]
    ForeignKeyCycle { path: String },

    #[error(
        "model '{model}' declares #[foreign_key] on the struct; a foreign key is a field typed Key<Model>"
    )]
    ForeignKeyIsNotAModelAttribute { model: String },

    #[error(
        "field '{field}' of model '{model}' declares #[foreign_key] but is not typed Key<Model>"
    )]
    ForeignKeyRequiresKeyField { field: String, model: String },

    #[error(
        "key field '{field}' of model '{model}' declares #[foreign_key] without on_delete; a key without the attribute takes no action on delete"
    )]
    ForeignKeyRequiresOnDelete { field: String, model: String },

    #[error(
        "relation '{relation}' of model '{model}' has many related rows through '{key}', which is unique; declare it with #[has_one]"
    )]
    HasManyOverUniqueKey {
        key: String,
        model: String,
        relation: String,
    },

    #[error(
        "relation '{relation}' of model '{model}' needs an index of its related model that leads with '{key}' and orders the related rows completely"
    )]
    HasManyRequiresOrderedIndex {
        key: String,
        model: String,
        relation: String,
    },

    #[error(
        "relation '{relation}' of model '{model}' has one related row through '{key}', which is not unique; declare it with #[has_many]"
    )]
    HasOneRequiresUniqueKey {
        key: String,
        model: String,
        relation: String,
    },

    #[error("failed to read the model attributes: {source}")]
    Index {
        #[from]
        source: AttributeError,
    },

    #[error(
        "model '{model}' declares an index over '{index}', which extends the unique key '{unique}'; a unique key already identifies one row"
    )]
    IndexExtendsUniqueKey {
        index: String,
        model: String,
        unique: String,
    },

    #[error(
        "the index '{name}' of table '{index_table}' collides with the constraint index of table '{constraint_table}'"
    )]
    IndexNameCollidesWithConstraintIndex {
        constraint_table: String,
        index_table: String,
        name: String,
    },

    #[error(
        "the index '{name}' of table '{index_table}' collides with the table of model '{table_model}'"
    )]
    IndexNameCollidesWithTableName {
        index_table: String,
        name: String,
        table_model: String,
    },

    #[error("model '{model}' derives an index name that is too long: {source}")]
    IndexNameTooLong {
        model: String,
        #[source]
        source: SchemaIdentifierNamingError,
    },

    #[error(
        "model '{model}' has an invalid column name '{column}'; it must be a snake_case identifier"
    )]
    InvalidColumnName { column: String, model: String },

    #[error(
        "model '{model}' has an invalid index name '{index}'; it must be a snake_case identifier"
    )]
    InvalidIndexName { index: String, model: String },

    #[error(
        "model '{model}' declares the relation name '{relation}', which is not a snake_case identifier"
    )]
    InvalidRelationName { model: String, relation: String },

    #[error(
        "model '{model}' has an invalid table name '{table}'; it must be a snake_case identifier"
    )]
    InvalidTableName { model: String, table: String },

    #[error(
        "key field '{field}' of model '{model}' references '{target}', an item of this crate that is not a #[model]"
    )]
    KeyTargetNotAModel {
        field: String,
        model: String,
        target: String,
    },

    #[error(
        "key field '{field}' of model '{model}' references '{target}', which is not an item of this crate"
    )]
    KeyTargetOutsideCrate {
        field: String,
        model: String,
        target: String,
    },

    #[error(
        "field '{field}' of model '{model}' has the type '{rust_type}', which resolves to '{resolved_type}' declared in this crate but is not a fieldless enum"
    )]
    LocalColumnTypeIsNotAnEnum {
        field: String,
        model: String,
        resolved_type: String,
        rust_type: String,
    },

    #[error("model '{model}' derives a minimum constraint name that is too long: {source}")]
    MinimumConstraintNameTooLong {
        model: String,
        #[source]
        source: SchemaIdentifierNamingError,
    },

    #[error(
        "column '{column}' of model '{model}' declares a minimum, which only applies to numeric columns"
    )]
    MinimumOnNonNumericColumn { column: String, model: String },

    #[error("model '{model}' is missing the required 'table' argument")]
    MissingTable { model: String },

    #[error(
        "#[{declaration}] of model '{model}' names '{field}', which is not a plain field identifier"
    )]
    ModelDeclarationFieldIsNotAnIdentifier {
        declaration: String,
        field: String,
        model: String,
    },

    #[error(
        "#[{declaration}] of model '{model}' names '{field}', which is not a field of the model"
    )]
    ModelDeclarationFieldNotDeclared {
        declaration: String,
        field: String,
        model: String,
    },

    #[error("#[{declaration}] of model '{model}' names the field '{field}' more than once")]
    ModelDeclarationRepeatsField {
        declaration: String,
        field: String,
        model: String,
    },

    #[error("#[{declaration}] of model '{model}' declares no fields")]
    ModelDeclarationRequiresFields { declaration: String, model: String },

    #[error(
        "#[{declaration}] of model '{model}' declares a single field; declare it on the field itself"
    )]
    ModelDeclarationRequiresSeveralFields { declaration: String, model: String },

    #[error(
        "field '{field}' of model '{model}' is typed as the model '{target}'; reference another model through Key<{target}>"
    )]
    ModelFieldRequiresKey {
        field: String,
        model: String,
        target: String,
    },

    #[error("model '{model}' declares an #[index] on the struct without a name")]
    ModelIndexRequiresName { model: String },

    #[error("'{model}' is annotated with #[model] but is not a struct")]
    ModelNotAStruct { model: String },

    #[error(
        "model '{model}' has a positional field at index {position}; a model has named fields only"
    )]
    ModelRequiresNamedFields { model: String, position: usize },

    #[error("model '{model}' declares no primary key")]
    ModelRequiresPrimaryKey { model: String },

    #[error("field '{field}' of model '{model}' is part of the primary key but is optional")]
    NullablePrimaryKeyField { field: String, model: String },

    #[error("field '{field}' of model '{model}' is part of a unique constraint but is optional")]
    NullableUniqueField { field: String, model: String },

    #[error(
        "field '{field}' of model '{model}' is a rust_decimal::Decimal without precision and scale"
    )]
    NumericColumnRequiresDigits { field: String, model: String },

    #[error(
        "field '{field}' of model '{model}' has the type '{rust_type}', which takes no NUMERIC precision or scale"
    )]
    NumericDigitsOnNonNumericColumn {
        field: String,
        model: String,
        rust_type: String,
    },

    #[error(
        "field '{field}' of model '{model}' declares a NUMERIC scale without a precision; both are required"
    )]
    NumericPrecisionMissing { field: String, model: String },

    #[error(
        "field '{field}' of model '{model}' declares the NUMERIC precision {precision}; the precision must be between 1 and 28, because rust_decimal::Decimal stores a 96-bit mantissa whose largest value is 79228162514264337593543950335"
    )]
    NumericPrecisionOutOfRange {
        field: String,
        model: String,
        precision: u32,
    },

    #[error(
        "field '{field}' of model '{model}' declares the NUMERIC scale {scale}, which exceeds its precision {precision}"
    )]
    NumericScaleExceedsPrecision {
        field: String,
        model: String,
        precision: u32,
        scale: u32,
    },

    #[error(
        "field '{field}' of model '{model}' declares a NUMERIC precision without a scale; both are required"
    )]
    NumericScaleMissing { field: String, model: String },

    #[error("model '{model}' derives a primary key index name that is too long: {source}")]
    PrimaryKeyIndexNameTooLong {
        model: String,
        #[source]
        source: SchemaIdentifierNamingError,
    },

    #[error(
        "field '{field}' of model '{model}' declares #[primary_key]; a single field declares #[column(primary_key)]"
    )]
    PrimaryKeyIsNotAFieldAttribute { field: String, model: String },

    #[error("the primary key of model '{model}' references itself through its keys")]
    PrimaryKeyReferenceCycle { model: String },

    #[error(
        "model '{model}' declares an index over '{columns}', which leads its primary key and duplicates its index"
    )]
    RedundantIndexOnPrimaryKeyColumns { columns: String, model: String },

    #[error(
        "model '{model}' declares an index over '{columns}', which leads a unique constraint and duplicates its index"
    )]
    RedundantIndexOnUniqueColumns { columns: String, model: String },

    #[error(
        "relation '{relation}' of model '{model}' names '{related}', which is not a #[model] of this crate"
    )]
    RelatedItemNotAModel {
        model: String,
        related: String,
        relation: String,
    },

    #[error(
        "relation '{relation}' of model '{model}' goes through '{key}', which is not a Key field of the related model"
    )]
    RelationKeyFieldNotAKey {
        key: String,
        model: String,
        relation: String,
    },

    #[error(
        "relation '{relation}' of model '{model}' goes through '{key}', which is not a field of the related model"
    )]
    RelationKeyFieldNotDeclared {
        key: String,
        model: String,
        relation: String,
    },

    #[error(
        "relation '{relation}' of model '{model}' names the key '{key}', which is not a plain field identifier"
    )]
    RelationKeyIsNotAnIdentifier {
        key: String,
        model: String,
        relation: String,
    },

    #[error(
        "relation '{relation}' of model '{model}' goes through '{key}', which references '{target}' instead"
    )]
    RelationKeyTargetsAnotherModel {
        key: String,
        model: String,
        relation: String,
        target: String,
    },

    #[error("relation '{relation}' of model '{model}' does not name the key it goes through")]
    RelationRequiresKey { model: String, relation: String },

    #[error("relation '{relation}' of model '{model}' does not name its related model")]
    RelationRequiresModel { model: String, relation: String },

    #[error("#[{declaration}] of model '{model}' does not name the relation")]
    RelationRequiresName { declaration: String, model: String },

    #[error(
        "key field '{field}' of model '{model}' sets its value to null on delete but is not optional"
    )]
    SetNullRequiresNullableKey { field: String, model: String },

    #[error("model '{model}' declares a table name that is too long: {source}")]
    TableNameTooLong {
        model: String,
        #[source]
        source: SchemaIdentifierNamingError,
    },

    #[error(
        "field '{field}' of model '{model}' has the type '{rust_type}'; a timestamp column is a chrono::DateTime<chrono::Utc>"
    )]
    TimestamptzRequiresUtc {
        field: String,
        model: String,
        rust_type: String,
    },

    #[error("field '{field}' of model '{model}' has no #[column] attribute")]
    UnattributedField { field: String, model: String },

    #[error(
        "key field '{field}' of model '{model}' is not indexed; an index, unique constraint or primary key must lead with it"
    )]
    UnindexedForeignKey { field: String, model: String },

    #[error(
        "field '{field}' of model '{model}' has the type '{rust_type}', which cannot be mapped to an SQL type"
    )]
    UninferrableColumnType {
        field: String,
        model: String,
        rust_type: String,
    },

    #[error("model '{model}' derives a unique index name that is too long: {source}")]
    UniqueIndexNameTooLong {
        model: String,
        #[source]
        source: SchemaIdentifierNamingError,
    },

    #[error(
        "field '{field}' of model '{model}' declares #[unique]; a single field declares #[column(unique)]"
    )]
    UniqueIsNotAFieldAttribute { field: String, model: String },

    #[error(
        "field '{field}' of model '{model}' declares the column default '{default}', which is not a variant of margaret::framework::model::column_default::ColumnDefault"
    )]
    UnknownColumnDefault {
        default: String,
        field: String,
        model: String,
    },

    #[error(
        "key field '{field}' of model '{model}' declares the on_delete action '{action}', which is not a variant of margaret::framework::model::on_delete::OnDelete"
    )]
    UnknownOnDeleteAction {
        action: String,
        field: String,
        model: String,
    },

    #[error(
        "field '{field}' of model '{model}' has the type '{rust_type}', which does not resolve to a path type"
    )]
    UnresolvableFieldType {
        field: String,
        model: String,
        rust_type: String,
    },

    #[error(
        "field '{field}' of model '{model}' wraps its value in '{wrapper}', which takes exactly one type argument"
    )]
    WrapperRequiresOneArgument {
        field: String,
        model: String,
        wrapper: String,
    },
}
