#[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
pub(crate) enum GeneratedFeature {
    AcceptedClients,
    AssetBag,
    AuthenticatedUsers,
    Console,
    Container,
    Http,
    Jwks,
    Middleware,
    Models,
    OAuthClients,
    OidcProvider,
    ResourceTokens,
    Schema,
    Scopes,
    Serves,
    Sessions,
    Shapes,
    TokenIssuance,
    TrustedIssuers,
    Views,
    Websockets,
}
