[package]
name = "margaret_provider_state_storage_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
chrono = { workspace = true }
ephemeral-postgres = { workspace = true }
margaret_model = { workspace = true }
margaret_oauth_vocabulary = { workspace = true }
margaret_provider_state_postgres = { workspace = true }
margaret_provider_state_storage = { workspace = true }
margaret_schema_postgres_tests = { path = "../margaret_schema_postgres_tests" }
margaret_token_digest = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
url = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[features]
tests_that_use_postgres = []

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
