[package]
name = "margaret_http_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
async-trait = { workspace = true }
margaret_http = { workspace = true }
margaret_http_uploaded_file = { workspace = true }
rcgen = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt-multi-thread"] }
tokio-rustls = { workspace = true }
tokio-util = { workspace = true }
url = { workspace = true }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
