[package]
name = "margaret_http_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
cookie = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
margaret_handler_error = { workspace = true }
margaret_http = { workspace = true }
margaret_http_uploaded_file = { workspace = true }
margaret_peer_identity = { workspace = true }
margaret_route_method = { workspace = true }
margaret_route_parameter_binding = { workspace = true }
rcgen = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt-multi-thread", "test-util"] }
tokio-rustls = { workspace = true }
tokio-util = { workspace = true }
url = { workspace = true }

[dev-dependencies]
futures-util = { workspace = true }
http-body = { workspace = true }
mime = { workspace = true }
spiffe = { workspace = true, features = ["spiffe-types"] }
tempfile = { workspace = true }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
