[package]
name = "margaret_token_signer_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
chrono = { workspace = true }
margaret_identity_session = { workspace = true }
margaret_jwks_keygen = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
margaret_token_signer = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
zeroize = { workspace = true }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
