[package]
name = "margaret_token_signer_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
chrono = { workspace = true }
margaret_identity_session = { workspace = true }
margaret_jose_parameters = { workspace = true }
margaret_jwks_keygen = { workspace = true }
margaret_jwt_verification_tests = { path = "../margaret_jwt_verification_tests" }
margaret_registered_claims = { workspace = true }
margaret_token_issuance = { workspace = true }
margaret_token_trust = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
margaret_jws_verification = { workspace = true }
margaret_jwt_verification = { workspace = true }
margaret_token_signer = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
