[package]
name = "margaret_server_origin"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Origins of the servers that the Margaret application framework serves."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
thiserror = { workspace = true }
url = { workspace = true }

[lints]
workspace = true
