[package]
name = "margaret_spiffe_svid_manager_tests"
version = "0.1.0"
edition = "2024"
autotests = false

[dependencies]
anyhow = { workspace = true }
libc = { workspace = true }
margaret_spiffe_svid_manager = { path = "../margaret_spiffe_svid_manager" }
margaret_sync_holder = { path = "../margaret_sync_holder" }
reqwest = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
spiffe = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "net", "process", "rt-multi-thread", "sync", "time"] }

[dev-dependencies]
futures-util = { workspace = true }
tokio-util = { workspace = true }
trzcina = { workspace = true }

[lints]
workspace = true

[[test]]
name = "integration"
path = "tests/main.rs"
