[package]
name = "margaret_jwks_codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
heck = { workspace = true }
margaret_attributes = { path = "../margaret_attributes" }
margaret_generated_module = { path = "../margaret_generated_module" }
proc-macro2 = { workspace = true }
quote = { workspace = true }

[lints]
workspace = true
