[package]
name = "margaret_model_facade"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "The framework facade that Margaret model crates generate their active record code against."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
margaret_active_record = { workspace = true }
margaret_database = { workspace = true }
margaret_macros = { workspace = true }
margaret_model = { workspace = true }
margaret_sql_identifier = { workspace = true }

[lints]
workspace = true
