[package]
name = "margaret_issuer_directory_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
async-trait = { workspace = true }
margaret_http = { workspace = true }
margaret_http_tests = { path = "../margaret_http_tests" }
margaret_issuer_directory = { workspace = true }
margaret_issuer_key_set = { workspace = true }
margaret_issuer_metadata = { workspace = true }
margaret_issuer_request = { workspace = true }
margaret_route_method = { workspace = true }
margaret_token_trust = { workspace = true }
margaret_trusted_issuer = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
tokio-util = { workspace = true }

[dev-dependencies]
margaret_bearer_token_verification = { workspace = true }
margaret_jwks_keygen_tests = { path = "../margaret_jwks_keygen_tests" }
margaret_jwks_roller = { workspace = true }
margaret_jwks_roller_server = { workspace = true }
margaret_jws_verification = { workspace = true }
margaret_jws_verification_tests = { path = "../margaret_jws_verification_tests" }
margaret_jwt_verification = { workspace = true }
margaret_jwt_verification_tests = { path = "../margaret_jwt_verification_tests" }
margaret_oidc_discovery = { workspace = true }
margaret_sync_holder = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "test-util"] }
trzcina = { workspace = true }

[[test]]
name = "main"
path = "tests/main.rs"

[lints]
workspace = true
