[package]
name = "margaret_http"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
futures-util = { workspace = true }
cookie = { workspace = true }
form_urlencoded = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true, features = ["http1", "server"] }
hyper-util = { workspace = true, features = ["http1", "server", "server-auto", "server-graceful", "service", "tokio"] }
margaret_http_uploaded_file = { path = "../margaret_http_uploaded_file" }
margaret_peer_identity = { path = "../margaret_peer_identity" }
margaret_route_parameter_binding = { path = "../margaret_route_parameter_binding" }
matchit = { workspace = true }
maud = { workspace = true }
mime = { workspace = true }
multer = { workspace = true }
percent-encoding = { workspace = true }
serde = { workspace = true }
rustls = { workspace = true }
serde_json = { workspace = true }
spiffe = { workspace = true, features = ["spiffe-types"] }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-util", "macros", "net", "rt"] }
tokio-rustls = { workspace = true }
tokio-util = { workspace = true }
tower = { workspace = true, features = ["util"] }

[dev-dependencies]
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt-multi-thread"] }

[lints]
workspace = true
