[package]
name = "margaret_tag_codegen"
version = "0.3.0"
edition.workspace = true
rust-version.workspace = true
description = "Dependency tag code generation for the Margaret application framework."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
margaret_attribute_arguments = { workspace = true }
margaret_attributes = { workspace = true }
syn = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
