pub mod attribute_args;
pub mod attribute_error;
pub mod attribute_index;
pub mod attribute_index_builder;
pub mod attribute_query;
pub mod attribute_selector;
pub mod canonical_path;
pub mod crate_root;
pub mod indexed_associated_type;
pub mod indexed_item;
pub mod indexed_method;
pub mod item_kind;
pub mod join_candidates;
pub mod matched_attribute;
pub mod path_tokens;
pub mod resolution;
pub mod resolve_struct;
pub mod resolve_unique;
pub mod struct_shape;

mod format_path;
mod module_walker;
