[package]
name = "margaret_console_argument_codegen"
version = "0.4.0"
edition.workspace = true
rust-version.workspace = true
description = "Console argument code generation for the Margaret application framework."
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
margaret_attribute_arguments = { workspace = true }
margaret_attributes = { workspace = true }
margaret_codegen_tokens = { workspace = true }
margaret_input_weaving = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
