[package]
name = "margaret_spiffe_svid_server_tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dev-dependencies]
margaret_spiffe_svid = { workspace = true }
margaret_peer_identity = { workspace = true }
margaret_spiffe_svid_server = { workspace = true }
margaret_spiffe_svid_tests = { path = "../margaret_spiffe_svid_tests" }
rustls = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
tokio-util = { workspace = true }
trzcina = { workspace = true }

[lints]
workspace = true

[[test]]
name = "integration"
path = "tests/main.rs"
