[package]
name = "margaret_websocket"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
hyper = { workspace = true, features = ["http1"] }
hyper-util = { workspace = true, features = ["tokio"] }
margaret_http = { path = "../margaret_http" }
margaret_route_parameter_binding = { path = "../margaret_route_parameter_binding" }
margaret_validation = { path = "../margaret_validation" }
margaret_websocket_session = { path = "../margaret_websocket_session" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync"] }
tokio-tungstenite = { workspace = true }
tokio-util = { workspace = true }
validator = { workspace = true }

[lints]
workspace = true
